server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8082

  cloud:
    gateway:
        routes:
          - id: EMPLOYEE-SERVICE
            uri: lb://EMPLOYEE-SERVICE
            predicates:
              - Path=/employee/**
            filters:
              - AuthenticationFilter

          - id: DEPARTMENT-SERVICE
            uri: lb://DEPARTMENT-SERVICE
            predicates:
              - Path=/department/**
            filters:
              - AuthenticationFilter

          - id: AUTH-SERVICE
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/Auth/**